Bugfix for previous MagicDNS incompatibility fix (prevent logging SERVFAIL lines when accept_dns is disabled)

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/init-magicdns-proxies/run
@@ -6,6 +6,12 @@ export LOG_FD
 # Runs the dnsmasq proxies initialization
 # ==============================================================================
 
+# Note: This service runs when userspace_networking is disabled, and
+# - when accept_dns is enabled, adds login server, log server and letsencrypt api to the black_white_list,
+#   to prevent DNS query loops (both egress and ingress proxies are running)
+# - when accept_dns is disabled, adds tailnet to the black_white_list,
+#   to prevent logging SERVFAIL by 100.100.100.100 for non-tailnet queries (only ingress proxy is running)
+
 readonly MAGIC_DNS_IPV4="100.100.100.100"
 readonly MAGIC_DNS_IPV6="fd7a:115c:a1e0::53"
 
@@ -19,6 +25,7 @@ declare invalid_dns_config
 
 declare login_server="${DEFAULT_LOGIN_SERVER}"
 declare -a black_white_list=()
+declare tailnet_domain
 
 # Check DNS configuration
 invalid_dns_config="true"
@@ -54,22 +61,33 @@ if bashio::var.true "${invalid_dns_config}"; then
   bashio::exit.nok
 fi
 
-# We have to be able to determine login_server from this address
-if ! login_server=$(awk -F[/:] '{print $4}' <<<"$(bashio::config "login_server")") || \
-  ! bashio::var.has_value "${login_server}"
-then
-  bashio::exit.nok "Determining host name from '$(bashio::config "login_server")' has failed"
-fi
-black_white_list+=("${login_server}")
+if bashio::config.true "accept_dns"; then
+  # We have to be able to determine login_server from this address
+  if ! login_server=$(awk -F[/:] '{print $4}' <<<"$(bashio::config "login_server")") || \
+    ! bashio::var.has_value "${login_server}"
+  then
+    bashio::exit.nok "Determining host name from '$(bashio::config "login_server")' has failed"
+  fi
+  black_white_list+=("${login_server}")
 
-# When log upload is enabled, resolve log server also
-if bashio::debug; then
-  black_white_list+=("${LOG_SERVER}")
-fi
+  # When log upload is enabled, resolve log server also
+  if bashio::debug; then
+    black_white_list+=("${LOG_SERVER}")
+  fi
 
-# If serve or funnel is used, resolve letsencrypt's api also
-if ! bashio::config.equals 'share_homeassistant' 'disabled'; then
-  black_white_list+=("${LETSENCRYPT_API}")
+  # If serve or funnel is used, resolve letsencrypt's api also
+  if ! bashio::config.equals 'share_homeassistant' 'disabled'; then
+    black_white_list+=("${LETSENCRYPT_API}")
+  fi
+else
+  # Add the tailnet domain as white list
+  if ! tailnet=$( \
+    /opt/tailscale status --json --peers=false --self=false \
+    | jq -re '.MagicDNSSuffix')
+  then
+    bashio::exit.nok "Determining tailnet name has failed"
+  fi
+  black_white_list+=("${tailnet}")
 fi
 
 printf "%s" "${black_white_list[@]/%/$'\n'}" > "${DNSMASQ_BLACK_WHITE_LIST_LOCATION}"
