Prevent logging SERVFAIL by MagicDNS, caused by Supervisor's hourly DNS tests (#636)

diff --git a/tailscale/rootfs/usr/bin/magicdns-ingress-proxy-forwarding b/tailscale/rootfs/usr/bin/magicdns-ingress-proxy-forwarding
--- a/tailscale/rootfs/usr/bin/magicdns-ingress-proxy-forwarding
+++ b/tailscale/rootfs/usr/bin/magicdns-ingress-proxy-forwarding
@@ -12,6 +12,13 @@ readonly DNSMASQ_INGRESS_PORT=53
 
 declare hassio_dns_ipv4
 declare hassio_dns_ipv6
+declare hassio_supervisor_ipv4
+declare hassio_supervisor_ipv6
+
+readonly HASSIO_DNS_IPV4_CACHE="/run/hassio_dns_ipv4.cache"
+readonly HASSIO_DNS_IPV6_CACHE="/run/hassio_dns_ipv6.cache"
+readonly HASSIO_SUPERVISOR_IPV4_CACHE="/run/hassio_supervisor_ipv4.cache"
+readonly HASSIO_SUPERVISOR_IPV6_CACHE="/run/hassio_supervisor_ipv6.cache"
 
 declare tailscale_address_ipv4
 declare tailscale_address_ipv6
@@ -27,15 +34,16 @@ function setup_forwarding() {
   local to_address="${8}"
   local to_port="${9}"
   local name="${10}"
+  local source_name="${11}"
 
-  bashio::log.info "Setting up ${name} for MagicDNS ingress proxy (${proto}, ${ip_version})"
+  bashio::log.info "Setting up ${name} for MagicDNS ingress proxy (${proto}, ${ip_version}, ${source_name})"
   if ${cmd} -t nat -S PREROUTING \
     | grep -Eq "^-A PREROUTING -s ${source_address//[\[\]]/}/${address_bits} -d ${from_address//[\[\]]/}/${address_bits} -i hassio -p ${proto} -m ${proto} --dport 53 -j DNAT --to-destination $(sed -r 's/(\[|\])/\\\1/g' <<< "${to_address}"):${to_port}$"
   then
-    bashio::log.notice "${name^} is already set for MagicDNS ingress proxy (${proto}, ${ip_version})"
+    bashio::log.notice "${name^} is already set for MagicDNS ingress proxy (${proto}, ${ip_version}, ${source_name})"
   else
     if ! ${cmd} -t nat "-${sub_cmd}" PREROUTING -s "${source_address//[\[\]]/}" -d "${from_address//[\[\]]/}" -i hassio -p "${proto}" --dport 53 -j DNAT --to-destination "${to_address}:${to_port}"; then
-      bashio::exit.nok "Setting up ${name} for MagicDNS ingress proxy is unsuccessful (${proto}, ${ip_version})"
+      bashio::exit.nok "Setting up ${name} for MagicDNS ingress proxy is unsuccessful (${proto}, ${ip_version}, ${source_name})"
     fi
   fi
 }
@@ -49,6 +57,7 @@ function remove_forwarding() {
   local to_address="${6}"
   local to_port="${7}"
   local name="${8}"
+  local source_name="${9}"
 
   local proto
 
@@ -57,43 +66,55 @@ function remove_forwarding() {
     | { grep -E "^-A PREROUTING -s ${source_address//[\[\]]/}/${address_bits} -d ${from_address//[\[\]]/}/${address_bits} -i hassio -p \S+ -m \S+ --dport 53 -j DNAT --to-destination $(sed -r 's/(\[|\])/\\\1/g' <<< "${to_address}"):${to_port}$" || true ;} \
     | sed -nr 's/^.*?-p\s(\S+).*$/\1/p')
   do
-    bashio::log.info "Removing ${name} for MagicDNS ingress proxy (${proto}, ${ip_version})"
+    bashio::log.info "Removing ${name} for MagicDNS ingress proxy (${proto}, ${ip_version}, ${source_name})"
     if ! ${cmd} -t nat -D PREROUTING -s "${source_address//[\[\]]/}" -d "${from_address//[\[\]]/}" -i hassio -p "${proto}" --dport 53 -j DNAT --to-destination "${to_address}:${to_port}"; then
-      bashio::log.warning "Removing ${name} for MagicDNS ingress proxy is unsuccessful (${proto}, ${ip_version})"
+      bashio::log.warning "Removing ${name} for MagicDNS ingress proxy is unsuccessful (${proto}, ${ip_version}, ${source_name})"
     fi
   done
 }
 
-function dig_hassio_dns() {
-  local type="${1}"
-  dig dns.local.hass.io "${type}" +short | { grep -Ev '^;|\.$|^$' || true ;} | head -n 1
-}
-
-# This is useful when stopping services and dig fails but we already added this value to iptables
-function get_hassio_dns_from_iptables() {
-  local cmd="${1}"
-  local address_bits="${2}"
-  local from_address="${3}"
-
-  ${cmd} -t nat -S PREROUTING \
-  | { grep -E "^-A PREROUTING -s \S+ -d ${from_address}/${address_bits} -i hassio -p udp -m udp --dport 53 -j DNAT --to-destination \S+$" || true ;} \
-  | sed -nr 's/^.*?-s\s([^\/]+)\/\d+\s-d.*$/\1/p' \
-  | head -n 1
+function dig_hassio_host() {
+  local host="${1}"
+  local type="${2}"
+  dig "${host}.local.hass.io" "${type}" +short | { grep -Ev '^;|\.$|^$' || true ;} | head -n 1
 }
 
 # Hassio DNS's IP addresses
 # For the status of IPv6 support see https://github.com/home-assistant/supervisor/issues/2133
-if ! hassio_dns_ipv4=$(dig_hassio_dns A) || \
-  ! hassio_dns_ipv6=$(dig_hassio_dns AAAA) || \
+if ! hassio_dns_ipv4=$(dig_hassio_host 'dns' A) || \
+  ! hassio_dns_ipv6=$(dig_hassio_host 'dns' AAAA) || \
   bashio::var.is_empty "${hassio_dns_ipv4-}" && bashio::var.is_empty "${hassio_dns_ipv6-}"
 then
-  if ! hassio_dns_ipv4=$(get_hassio_dns_from_iptables "iptables" "32" "${MAGIC_DNS_IPV4}") || \
-    ! hassio_dns_ipv6=$(get_hassio_dns_from_iptables "ip6tables" "128" "${MAGIC_DNS_IPV6}") || \
+  # This is useful when stopping services and dig fails but we already stored this value
+  if ! hassio_dns_ipv4="$(<"${HASSIO_DNS_IPV4_CACHE}")" || \
+    ! hassio_dns_ipv6="$(<"${HASSIO_DNS_IPV6_CACHE}")" || \
     bashio::var.is_empty "${hassio_dns_ipv4-}" && bashio::var.is_empty "${hassio_dns_ipv6-}"
   then
     bashio::exit.nok "Failed to resolve Home Assistant's DNS address"
   fi
+else
+  printf "%s" "${hassio_dns_ipv4-}" > "${HASSIO_DNS_IPV4_CACHE}"
+  printf "%s" "${hassio_dns_ipv6-}" > "${HASSIO_DNS_IPV6_CACHE}"
 fi
+
+# Supervisor's IP addresses
+# For the status of IPv6 support see https://github.com/home-assistant/supervisor/issues/2133
+if ! hassio_supervisor_ipv4=$(dig_hassio_host 'supervisor' A) || \
+  ! hassio_supervisor_ipv6=$(dig_hassio_host 'supervisor' AAAA) || \
+  bashio::var.is_empty "${hassio_supervisor_ipv4-}" && bashio::var.is_empty "${hassio_supervisor_ipv6-}"
+then
+  # This is useful when stopping services and dig fails but we already stored this value
+  if ! hassio_supervisor_ipv4="$(<"${HASSIO_SUPERVISOR_IPV4_CACHE}")" || \
+    ! hassio_supervisor_ipv6="$(<"${HASSIO_SUPERVISOR_IPV6_CACHE}")" || \
+    bashio::var.is_empty "${hassio_supervisor_ipv4-}" && bashio::var.is_empty "${hassio_supervisor_ipv6-}"
+  then
+    bashio::exit.nok "Failed to resolve Home Assistant's Supervisor address"
+  fi
+else
+  printf "%s" "${hassio_supervisor_ipv4-}" > "${HASSIO_SUPERVISOR_IPV4_CACHE}"
+  printf "%s" "${hassio_supervisor_ipv6-}" > "${HASSIO_SUPERVISOR_IPV6_CACHE}"
+fi
+
 # Tailscale's local IP addresses
 if bashio::var.equals "${2-}" "forwarding"; then
   if ! tailscale_address_ipv4=$(/opt/tailscale ip -4) || \
@@ -107,6 +128,11 @@ if bashio::var.equals "${2-}" "forwarding"; then
   then
     bashio::exit.nok "Failed to retrieve Tailscale's local address with matching IP version (v4 or v6) to Home Assistant's DNS address"
   fi
+  if (bashio::var.has_value "${hassio_supervisor_ipv4-}" && bashio::var.is_empty "${tailscale_address_ipv4-}") || \
+    (bashio::var.has_value "${hassio_supervisor_ipv6-}" && bashio::var.is_empty "${tailscale_address_ipv6-}")
+  then
+    bashio::exit.nok "Failed to retrieve Tailscale's local address with matching IP version (v4 or v6) to Home Assistant's Supervisor address"
+  fi
 fi
 
 case "${1-}-${2-}" in
@@ -115,38 +141,66 @@ case "${1-}-${2-}" in
     # This temporary trick is needed, because when TS starts, it adds a general ACCEPT FORWARD line in front of existing settings,
     # so we have to drop it during PREROUTING.
     if bashio::var.has_value "${hassio_dns_ipv4-}"; then
-      setup_forwarding "iptables" "I" "udp" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}"
-      setup_forwarding "iptables" "I" "tcp" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}"
+      setup_forwarding "iptables" "I" "udp" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}" "DNS"
+      setup_forwarding "iptables" "I" "tcp" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}" "DNS"
     fi
     if bashio::var.has_value "${hassio_dns_ipv6-}"; then
-      setup_forwarding "ip6tables" "I" "udp" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}"
-      setup_forwarding "ip6tables" "I" "tcp" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}"
+      setup_forwarding "ip6tables" "I" "udp" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}" "DNS"
+      setup_forwarding "ip6tables" "I" "tcp" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}" "DNS"
+    fi
+    if bashio::var.has_value "${hassio_supervisor_ipv4-}"; then
+      setup_forwarding "iptables" "I" "udp" "IPv4" "32" "${hassio_supervisor_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}" "Supervisor"
+      setup_forwarding "iptables" "I" "tcp" "IPv4" "32" "${hassio_supervisor_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}" "Supervisor"
+    fi
+    if bashio::var.has_value "${hassio_supervisor_ipv6-}"; then
+      setup_forwarding "ip6tables" "I" "udp" "IPv6" "128" "${hassio_supervisor_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}" "Supervisor"
+      setup_forwarding "ip6tables" "I" "tcp" "IPv6" "128" "${hassio_supervisor_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}" "Supervisor"
     fi
     ;;
   setup-forwarding)
     if bashio::var.has_value "${hassio_dns_ipv4-}"; then
-      setup_forwarding "iptables" "A" "udp" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}"
-      setup_forwarding "iptables" "A" "tcp" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}"
+      setup_forwarding "iptables" "A" "udp" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}" "DNS"
+      setup_forwarding "iptables" "A" "tcp" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}" "DNS"
     fi
     if bashio::var.has_value "${hassio_dns_ipv6-}"; then
-      setup_forwarding "ip6tables" "A" "udp" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}"
-      setup_forwarding "ip6tables" "A" "tcp" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}"
+      setup_forwarding "ip6tables" "A" "udp" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}" "DNS"
+      setup_forwarding "ip6tables" "A" "tcp" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}" "DNS"
+    fi
+    if bashio::var.has_value "${hassio_supervisor_ipv4-}"; then
+      setup_forwarding "iptables" "A" "udp" "IPv4" "32" "${hassio_supervisor_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}" "Supervisor"
+      setup_forwarding "iptables" "A" "tcp" "IPv4" "32" "${hassio_supervisor_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}" "Supervisor"
+    fi
+    if bashio::var.has_value "${hassio_supervisor_ipv6-}"; then
+      setup_forwarding "ip6tables" "A" "udp" "IPv6" "128" "${hassio_supervisor_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}" "Supervisor"
+      setup_forwarding "ip6tables" "A" "tcp" "IPv6" "128" "${hassio_supervisor_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}" "Supervisor"
     fi
     ;;
   remove-drop)
     if bashio::var.has_value "${hassio_dns_ipv4-}"; then
-      remove_forwarding "iptables" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}"
+      remove_forwarding "iptables" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}" "DNS"
     fi
     if bashio::var.has_value "${hassio_dns_ipv6-}"; then
-      remove_forwarding "ip6tables" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}"
+      remove_forwarding "ip6tables" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}" "DNS"
+    fi
+    if bashio::var.has_value "${hassio_supervisor_ipv4-}"; then
+      remove_forwarding "iptables" "IPv4" "32" "${hassio_supervisor_ipv4}" "${MAGIC_DNS_IPV4}" "127.0.0.1" "0" "${2}" "Supervisor"
+    fi
+    if bashio::var.has_value "${hassio_supervisor_ipv6-}"; then
+      remove_forwarding "ip6tables" "IPv6" "128" "${hassio_supervisor_ipv6}" "${MAGIC_DNS_IPV6}" "[::1]" "0" "${2}" "Supervisor"
     fi
     ;;
   remove-forwarding)
     if bashio::var.has_value "${hassio_dns_ipv4-}"; then
-      remove_forwarding "iptables" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}"
+      remove_forwarding "iptables" "IPv4" "32" "${hassio_dns_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}" "DNS"
     fi
     if bashio::var.has_value "${hassio_dns_ipv6-}"; then
-      remove_forwarding "ip6tables" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}"
+      remove_forwarding "ip6tables" "IPv6" "128" "${hassio_dns_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}" "DNS"
+    fi
+    if bashio::var.has_value "${hassio_supervisor_ipv4-}"; then
+      remove_forwarding "iptables" "IPv4" "32" "${hassio_supervisor_ipv4}" "${MAGIC_DNS_IPV4}" "${tailscale_address_ipv4}" "${DNSMASQ_INGRESS_PORT}" "${2}" "Supervisor"
+    fi
+    if bashio::var.has_value "${hassio_supervisor_ipv6-}"; then
+      remove_forwarding "ip6tables" "IPv6" "128" "${hassio_supervisor_ipv6}" "${MAGIC_DNS_IPV6}" "[${tailscale_address_ipv6}]" "${DNSMASQ_INGRESS_PORT}" "${2}" "Supervisor"
     fi
     ;;
   *)
