add rules only when multiple routing tables are enabled

diff --git a/tailscale/rootfs/usr/bin/protect-subnet-routes b/tailscale/rootfs/usr/bin/protect-subnet-routes
--- a/tailscale/rootfs/usr/bin/protect-subnet-routes
+++ b/tailscale/rootfs/usr/bin/protect-subnet-routes
@@ -6,8 +6,13 @@
 # ==============================================================================
 
 declare -a routes=()
+declare ipv4_multiple_tables_enabled
+declare ipv6_multiple_tables_enabled
+declare protected_routes=0
 
 if bashio::config.false "userspace_networking"; then
+  ipv4_multiple_tables_enabled=$(zcat /proc/config.gz | grep -Ec '^CONFIG_IP_MULTIPLE_TABLES=y$' || true)
+  ipv6_multiple_tables_enabled=$(zcat /proc/config.gz | grep -Ec '^CONFIG_IPV6_MULTIPLE_TABLES=y$' || true)
   bashio::cache.flush_all
   readarray -t routes < <(subnet-routes)
   if (( 0 < ${#routes[@]} )); then
@@ -15,11 +20,26 @@ if bashio::config.false "userspace_networking"; then
     bashio::log.info "to prevent routing local subnets if the same subnet is routed within your tailnet."
   fi
   for route in "${routes[@]}"; do
-    bashio::log.info "Adding route ${route} to ip rules"
     if [[ "${route}" =~ .*:.* ]]; then
-      ip -6 rule add to "${route}" priority 5001 table main
+      if (( 0 == ${ipv6_multiple_tables_enabled} )); then
+        bashio::log.warning "IPv6 multiple routing tables are not enabled, skip adding route ${route} to ip rules"
+      else
+        bashio::log.info "Adding route ${route} to ip rules"
+        ip -6 rule add to "${route}" priority 5001 table main
+        (( protected_routes+=1 ))
+      fi
     else
-      ip -4 rule add to "${route}" priority 5001 table main
+      if (( 0 == ${ipv4_multiple_tables_enabled} )); then
+        bashio::log.warning "IPv4 multiple routing tables are not enabled, skip adding route ${route} to ip rules"
+      else
+        bashio::log.info "Adding route ${route} to ip rules"
+        ip -4 rule add to "${route}" priority 5001 table main
+        (( protected_routes+=1 ))
+      fi
     fi
   done
+  if (( 0 < ${#routes[@]} && 0 == ${protected_routes} )); then
+    bashio::log.error "Can't protect any subnets"
+    bashio::exit.nok
+  fi
 fi
