test pipefail

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/tailscaled/run
@@ -28,6 +28,10 @@ if bashio::config.has_value "proxy_port"; then
   options+=(--outbound-http-proxy-listen=127.0.0.1:"$(bashio::config "proxy_port")")
 fi
 
+echo $-
+echo $SHELLOPTS
+false | true && echo '*** pipefail is NOT set ***'
+
 # Run Tailscale
 if bashio::debug ; then
   exec /opt/tailscaled "${options[@]}"
