make https port configurable

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/proxy/run
@@ -5,36 +5,57 @@
 # Enables Tailscale Proxy feature
 # ==============================================================================
 
+declare https_port
 declare domain
 
-# Check if Tailscale HTTPS is enabled
-if ! /opt/tailscale status --self=true --peers=false --json \
-  | jq -rce '.Self.CapMap | has("https")' > /dev/null;
-then
-  bashio::log.error "Tailscale's HTTPS support is disabled"
+# Tailscale serve and funnel configuration is persistent between restarts
+# Disable previously configured tailscale serve functionality with deleting the tailscale serve configuration
+if ! /opt/tailscale serve reset; then
+  bashio::log.error "Unable to reset Tailscale Proxy settings"
   bashio::exit.nok
 fi
 
-domain=$(/opt/tailscale status --self=true --peers=false --json | jq -rc ".CertDomains[0]")
+# Enable proxy service only when it has been explicitly enabled
+if bashio::config.true 'proxy'; then
 
-# Checking if SSL is used
-if bashio::var.true "$(bashio::core.ssl)"; then
-  bashio::log.error "Tailscale's HTTPS support is enabled, but Home Assistant is not accessible through plain HTTP connection"
-  bashio::exit.nok
-fi
+  https_port=$(bashio::addon.port 443)
 
-# Test Home Assistant's HTTP reverse proxy configuration
-if (( 200 != $(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:$(bashio::core.port)" -H "X-Forwarded-For: 127.0.0.1") )); then
-  bashio::log.error "Unable to connect to Home Assistant on http://127.0.0.1:$(bashio::core.port)"
+  # Check if HTTPS port is configured properly
+  if ! bashio::var.has_value "${https_port}"; then
+    bashio::log.error "No HTTPS port is configured"
+    bashio::exit.nok
+  fi
+
+  # Check if Tailscale HTTPS is enabled
+  if ! /opt/tailscale status --self=true --peers=false --json \
+    | jq -rce '.Self.CapMap | has("https")' > /dev/null;
+  then
+    bashio::log.error "Tailscale's HTTPS support is disabled"
+    bashio::exit.nok
+  fi
+
+  domain=$(/opt/tailscale status --self=true --peers=false --json | jq -rc ".CertDomains[0]")
+
+  # Checking if SSL is used
+  if bashio::var.true "$(bashio::core.ssl)"; then
+    bashio::log.error "Tailscale's HTTPS support is enabled, but Home Assistant is not accessible through plain HTTP connection"
+    bashio::exit.nok
+  fi
+
+  # Test Home Assistant's HTTP reverse proxy configuration
+  if (( 200 != $(curl -s -o /dev/null -w "%{http_code}" "http://127.0.0.1:$(bashio::core.port)" -H "X-Forwarded-For: 127.0.0.1") )); then
+    bashio::log.error "Unable to connect to Home Assistant on http://127.0.0.1:$(bashio::core.port)"
   bashio::log.error "Please check your configuration based on the add-on's documentation under \"Option: proxy\""
-  bashio::exit.nok
-fi
+    bashio::exit.nok
+  fi
 
-# Set up proxy
-if ! /opt/tailscale serve https:443 / "http://127.0.0.1:$(bashio::core.port)"; then
-  bashio::log.error "Unable to configure Tailscale Proxy"
-  bashio::exit.nok
+  # Set up proxy
+  if ! /opt/tailscale serve "https:${https_port}" / "http://127.0.0.1:$(bashio::core.port)"; then
+    bashio::log.error "Unable to configure Tailscale Proxy"
+    bashio::exit.nok
+  fi
+  bashio::log.info "Tailscale Proxy is enabled:"
+  bashio::log.info "  Your Home Assistant instance is available within your tailnet VPN at"
+  bashio::log.info "  https://${domain}:${https_port}"
+
 fi
-bashio::log.info "Tailscale Proxy is enabled:"
-bashio::log.info "  Your Home Assistant instance is available within your tailnet VPN at"
-bashio::log.info "  https://${domain}"
