fix proxy and funnel

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/post-tailscaled/run
@@ -89,6 +89,18 @@ do
   sleep 2
 done
 
+# Note: Tailscale serve and funnel configuration is persistent between restarts,
+#       we have to disable them, then reenable them if they are required
+# Note: If a tailnet node is renamed, there will be deprecated entries in status json
+#       under .Web.<different-domain:443>,
+#       those can be removed only with reseting the serve configuration
+if ! /opt/tailscale serve reset || \
+  ! /opt/tailscale funnel 443 off;
+then
+  bashio::log.error "Unable to reset Tailscale Proxy and Tailscale Funnel settings"
+  bashio::exit.nok
+fi
+
 bashio::log.info "Tailscale is running"
 
 # Warn about key expiration
