Refactor slow activities from nm-dispatcher script into separate listener service (#680)
Co-authored-by: Franck Nijhof <git@frenck.dev>

diff --git a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/nm-dispatcher/finish b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/nm-dispatcher/finish
--- a/tailscale/rootfs/etc/s6-overlay/s6-rc.d/nm-dispatcher/finish
+++ b/tailscale/rootfs/etc/s6-overlay/s6-rc.d/nm-dispatcher/finish
@@ -2,21 +2,19 @@
 # shellcheck shell=bash
 # ==============================================================================
 # Home Assistant Community App: Tailscale
-# Take down the S6 supervision tree when protect-subnets fails
+# Take down the S6 supervision tree when nm-dispatcher fails
 # ==============================================================================
 readonly exit_code_container=$(</run/s6-linux-init-container-results/exitcode)
 readonly exit_code_service="${1}"
 readonly exit_code_signal="${2}"
-readonly service="protect-subnets"
-
-unprotect-subnet-routes
+readonly service="nm-dispatcher"
 
 bashio::log.info \
   "Service ${service} exited with code ${exit_code_service}" \
   "(by signal ${exit_code_signal})"
 
 if [[ "${exit_code_service}" -eq 256 ]]; then
-  if [[ "${exit_code_container}" -eq 0 ]]; then
+  if [[ "${exit_code_signal}" -ne 15 && "${exit_code_container}" -eq 0 ]]; then
     echo $((128 + $exit_code_signal)) > /run/s6-linux-init-container-results/exitcode
   fi
   [[ "${exit_code_signal}" -eq 15 ]] && exec /run/s6/basedir/bin/halt
@@ -24,5 +22,9 @@ elif [[ "${exit_code_service}" -ne 0 ]]; then
   if [[ "${exit_code_container}" -eq 0 ]]; then
     echo "${exit_code_service}" > /run/s6-linux-init-container-results/exitcode
   fi
-  exec /run/s6/basedir/bin/halt
+  if ! bashio::fs.file_exists /run/s6_has_started; then
+    exit 125
+  else
+    exec /run/s6/basedir/bin/halt
+  fi
 fi
